project_name: hotline
version: 2
before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin


archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  draft: true
  extra_files:
    - glob: README.md

brews:
  - name: hotline
    description: "A client-side workflow engine/executor for AI applications."
    directory: Formula
    repository:
      owner: leslieleung
      name: homebrew-tap
    skip_upload: auto
    homepage: https://github.com/leslieleung/hotline

